// <auto-generated />
namespace ERPComercial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Gustavo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gustavo));
        
        string IMigrationMetadata.Id
        {
            get { return "201902041413493_Gustavo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
